# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kairos.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kairos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ckairos.proto\x12\tkairos.v1\"g\n\x0b\x46\x65\x61tureView\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07project\x18\x02 \x01(\t\x12\x13\n\x0b\x65ntity_name\x18\x03 \x01(\t\x12$\n\x08\x66\x65\x61tures\x18\x04 \x03(\x0b\x32\x12.kairos.v1.Feature\"&\n\x07\x46\x65\x61ture\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x64type\x18\x02 \x01(\t\"_\n\x18GetOnlineFeaturesRequest\x12\x19\n\x11\x66\x65\x61ture_view_name\x18\x01 \x01(\t\x12\x11\n\tentity_id\x18\x02 \x01(\t\x12\x15\n\rfeature_names\x18\x03 \x03(\t\"\x8c\x01\n\x19GetOnlineFeaturesResponse\x12@\n\x06values\x18\x01 \x03(\x0b\x32\x30.kairos.v1.GetOnlineFeaturesResponse.ValuesEntry\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32u\n\x13\x46\x65\x61tureStoreService\x12^\n\x11GetOnlineFeatures\x12#.kairos.v1.GetOnlineFeaturesRequest\x1a$.kairos.v1.GetOnlineFeaturesResponseBCZAgithub.com/kairos-platform/services/go-feature-server/pb;kairospbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kairos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZAgithub.com/kairos-platform/services/go-feature-server/pb;kairospb'
  _globals['_GETONLINEFEATURESRESPONSE_VALUESENTRY']._loaded_options = None
  _globals['_GETONLINEFEATURESRESPONSE_VALUESENTRY']._serialized_options = b'8\001'
  _globals['_FEATUREVIEW']._serialized_start=27
  _globals['_FEATUREVIEW']._serialized_end=130
  _globals['_FEATURE']._serialized_start=132
  _globals['_FEATURE']._serialized_end=170
  _globals['_GETONLINEFEATURESREQUEST']._serialized_start=172
  _globals['_GETONLINEFEATURESREQUEST']._serialized_end=267
  _globals['_GETONLINEFEATURESRESPONSE']._serialized_start=270
  _globals['_GETONLINEFEATURESRESPONSE']._serialized_end=410
  _globals['_GETONLINEFEATURESRESPONSE_VALUESENTRY']._serialized_start=365
  _globals['_GETONLINEFEATURESRESPONSE_VALUESENTRY']._serialized_end=410
  _globals['_FEATURESTORESERVICE']._serialized_start=412
  _globals['_FEATURESTORESERVICE']._serialized_end=529
# @@protoc_insertion_point(module_scope)
