# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import kairos_pb2 as kairos__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kairos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FeatureStoreServiceStub(object):
    """--- 2. Service Definition (The Go Server) ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOnlineFeatures = channel.unary_unary(
                '/kairos.v1.FeatureStoreService/GetOnlineFeatures',
                request_serializer=kairos__pb2.GetOnlineFeaturesRequest.SerializeToString,
                response_deserializer=kairos__pb2.GetOnlineFeaturesResponse.FromString,
                _registered_method=True)


class FeatureStoreServiceServicer(object):
    """--- 2. Service Definition (The Go Server) ---

    """

    def GetOnlineFeatures(self, request, context):
        """Used by the Python SDK to fetch features for Model Inference
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeatureStoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOnlineFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOnlineFeatures,
                    request_deserializer=kairos__pb2.GetOnlineFeaturesRequest.FromString,
                    response_serializer=kairos__pb2.GetOnlineFeaturesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kairos.v1.FeatureStoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kairos.v1.FeatureStoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FeatureStoreService(object):
    """--- 2. Service Definition (The Go Server) ---

    """

    @staticmethod
    def GetOnlineFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kairos.v1.FeatureStoreService/GetOnlineFeatures',
            kairos__pb2.GetOnlineFeaturesRequest.SerializeToString,
            kairos__pb2.GetOnlineFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
